In [7]:
import json
import shutil
import pandas as pd
import numpy as np
from glob import glob
from tqdm import tqdm

In [ ]:
df = pd.read_csv('sites/csv/bafing_chimp_video_data.csv')

In [ ]:
annotation_df = pd.read_excel('maureen_annotations.xlsx')
annotation_df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'], inplace=True)

In [10]:
annotation_df.columns

NameError: name 'annotation_df' is not defined

In [4]:
annotation_df.behavioral_context.value_counts()

travel                     20456
tool use termites           6164
feeding                     4917
tool use                    3940
resting                     3162
unclear                     2667
climbing                    1680
camera reaction             1465
displaying                   804
no                           693
grooming                     689
tool use unknown             590
playing                      587
tool use algae               576
tool use ants                385
tool use nuts                329
aggression                   280
tool use stone throwing      211
yes                          182
sexual                       158
greeting                      85
reassurance                   61
tool use honey                 2
displaying                     1
Name: behavioral_context, dtype: int64

In [5]:
# annotation_df.location_metadata.unique()

In [6]:
annotation_df.head()

,new_row_id,country,research_site,genus,species,cam_coverage_area,location_metadata,habitat,utm_zone,utm_long,...,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,Unnamed: 36,Unnamed: 37,subdir_video
0,1,liberia,east_nimba,Pan,troglodytes verus,10.12,trail,"forest - mixed, closed understorey",29n,549326,...,NaN,NaN,NaN,feeding,NaN,feeding,60s_video,NaN,NaN,nim_vid08_0549326_0825088_20130927/ek000055
1,2,liberia,east_nimba,Pan,troglodytes verus,10.12,trail,"forest - mixed, closed understorey",29n,549326,...,NaN,NaN,NaN,feeding,NaN,NaN,60s_video,NaN,NaN,nim_vid08_0549326_0825088_20130927/ek000055
2,3,liberia,east_nimba,Pan,troglodytes verus,10.12,trail,"forest - mixed, closed understorey",29n,549326,...,NaN,NaN,NaN,feeding,NaN,NaN,60s_video,NaN,NaN,nim_vid08_0549326_0825088_20130927/ek000055
3,4,liberia,east_nimba,Pan,troglodytes verus,10.12,trail,"forest - mixed, closed understorey",29n,549326,...,NaN,NaN,NaN,feeding,NaN,NaN,60s_video,NaN,NaN,nim_vid08_0549326_0825088_20130927/ek000055
4,5,liberia,east_nimba,Pan,troglodytes verus,10.12,trail,"forest - mixed, closed understorey",29n,549326,...,NaN,NaN,NaN,feeding,NaN,NaN,60s_video,NaN,NaN,nim_vid08_0549326_0825088_20130927/ek000055

In [7]:
# annotation_df[(annotation_df.country=='uganda') & (annotation_df.research_site=='ngogo')].subdir_video.str.split('_').str[0].unique()
# annotation_df[(annotation_df.max_number_chimps_per_video==1)].country.value_counts()

In [8]:
annotation_df.country.value_counts()[:15]

guinea          9801
senegal         8289
uganda          6019
gabon           5067
cotedivoire     4304
guineabissau    3750
cameroon        3408
rcongo          2975
liberia         1608
tanzania        1341
mali            1005
nigeria          872
sierraleone      805
rwanda           750
drc              406
Name: country, dtype: int64

In [9]:
annotation_df[(annotation_df.country=='cotedivoire')].research_site.value_counts()

cnpw          2081
djouroutou     544
taie           501
tair           494
geprenaf       439
cnpe           160
mt_sangbe       85
Name: research_site, dtype: int64

In [9]:
annotation_df[(annotation_df.country=='cotedivoire')]

,new_row_id,country,research_site,genus,species,cam_coverage_area,location_metadata,habitat,utm_zone,utm_long,...,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,Unnamed: 36,Unnamed: 37,subdir_video
655,1,cotedivoire,djouroutou,Pan,troglodytes verus,4.9,trail,forest - seasonally inundated,29n,697583,...,NaN,NaN,NaN,camera reaction,NaN,camera reaction,60s_video,NaN,NaN,djo_cam02_0697583_0599133_20121223/ek000015
656,2,cotedivoire,djouroutou,Pan,troglodytes verus,4.9,trail,forest - seasonally inundated,29n,697583,...,NaN,NaN,NaN,camera reaction,NaN,camera reaction; in the back with the adult,60s_video,NaN,NaN,djo_cam02_0697583_0599133_20121223/ek000015
657,3,cotedivoire,djouroutou,Pan,troglodytes verus,4.9,trail,forest - seasonally inundated,29n,697583,...,NaN,NaN,NaN,camera reaction,NaN,ventral infant,60s_video,NaN,NaN,djo_cam02_0697583_0599133_20121223/ek000015
658,4,cotedivoire,djouroutou,Pan,troglodytes verus,4.9,trail,forest - seasonally inundated,29n,697583,...,NaN,NaN,NaN,camera reaction,NaN,NaN,60s_video,NaN,NaN,djo_cam02_0697583_0599133_20121223/ek000015
659,5,cotedivoire,djouroutou,Pan,troglodytes verus,4.9,trail,forest - seasonally inundated,29n,697583,...,NaN,NaN,NaN,grooming,NaN,same individual from last video; interaction w...,60s_video,NaN,NaN,djo_cam02_0697583_0599133_20121223/ek000016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47558,435,cotedivoire,geprenaf,Pan,troglodytes verus,14,trail,"forest <U+0096> mixed, closed understorey",30n,382247,...,no,no,no,travel,NaN,datestamp changed to 2/13 (was originally list...,60s_video,NaN,NaN,gep_vid04_0382247_0967053_20140316/pict0013
47559,436,cotedivoire,geprenaf,Pan,troglodytes verus,14,trail,"forest <U+0096> mixed, closed understorey",30n,382247,...,no,no,yes,travel,NaN,datestamp changed to 2/13 (was originally list...,60s_video,NaN,NaN,gep_vid04_0382247_0967053_20140316/pict0013
47560,437,cotedivoire,geprenaf,Pan,troglodytes verus,14,trail,"forest <U+0096> mixed, closed understorey",30n,382247,...,no,no,yes,travel,NaN,datestamp changed to 2/13 (was originally list...,60s_video,NaN,NaN,gep_vid04_0382247_0967053_20140316/pict0013
47561,438,cotedivoire,geprenaf,Pan,troglodytes verus,14,trail,"forest <U+0096> mixed, closed understorey",30n,382247,...,no,no,yes,travel,NaN,datestamp changed to 2/13 (was originally list...,60s_video,NaN,NaN,gep_vid04_0382247_0967053_20140316/pict0013
47562,439,cotedivoire,geprenaf,Pan,troglodytes verus,14,trail,"forest <U+0096> mixed, closed understorey",30n,382247,...,no,no,yes,travel,NaN,young juvenile,60s_video,NaN,NaN,gep_vid04_0382247_0967053_20140503/pict0009

In [6]:
annotation_df[(annotation_df.country=='cotedivoire')&(annotation_df.research_site=='mt_sangbe')].head()

NameError: name 'annotation_df' is not defined

**What do we have?**

In [35]:
nigeria_singles = annotation_df[(annotation_df.max_number_chimps_per_video==1) & (annotation_df.country=='nigeria')].subdir_video.str.split('/').str.join('_').tolist()
len(nigeria_singles)

106

In [36]:
local_filenames = glob('/home/dl18206/Desktop/phd/data/panaf/chimp_annotations/videos/**/*.mp4', recursive=True)
local_filenames = [x.split('/')[-2:] for x in local_filenames]
local_filenames = [x[-1].split('.')[0].lower() for x in local_filenames]

In [37]:
len(local_filenames)

294

In [ ]:
[x for x in nigeria_singles if x in local_filenames]

In [14]:
# We know there are duplicates in here...
len(set(local_filenames)), len(local_filenames)

(294, 294)

In [38]:
local_filenames = glob('/home/dl18206/Desktop/phd/data/panaf/chimp_videos/drc/**/*.mp4', recursive=True)
local_filenames = [x.split('/')[-2:] for x in local_filenames]
local_filenames = ["/".join([x[0], x[-1].split('.')[0]]).lower() for x in local_filenames]

In [82]:
drc = annotation_df[(annotation_df.max_number_chimps_per_video==1) & (annotation_df.country=='drc')]

In [39]:
x = 'Gis_vid4_763441_9798666_20131111/PICT0033'.lower()
annotation_df[(annotation_df.max_number_chimps_per_video==1) & (annotation_df.country=='rwanda')].head()

,new_row_id,country,research_site,genus,species,cam_coverage_area,location_metadata,habitat,utm_zone,utm_long,...,tool_use,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,Unnamed: 36,Unnamed: 37
0,1,rwanda,gishwati,Pan,troglodytes schweinfurthii,NaN,beehive,forest - young secondary,35n,762418.0,...,no,no,no,yes,camera reaction,NaN,NaN,60s_video,NaN,NaN
10,11,rwanda,gishwati,Pan,troglodytes schweinfurthii,7.28,trail,forest - young secondary,35n,762955.0,...,no,no,no,yes,resting,NaN,NaN,60s_video,NaN,NaN
17,18,rwanda,gishwati,Pan,troglodytes schweinfurthii,7.28,trail,forest - young secondary,35n,762955.0,...,no,no,no,no,travel,NaN,NaN,60s_video,NaN,NaN
18,19,rwanda,gishwati,Pan,troglodytes schweinfurthii,7.28,trail,forest - young secondary,35n,762955.0,...,no,no,no,yes,travel,NaN,NaN,60s_video,NaN,NaN
24,25,rwanda,gishwati,Pan,troglodytes schweinfurthii,7.28,trail,forest - young secondary,35n,762955.0,...,no,no,no,no,travel,NaN,NaN,60s_video,NaN,NaN

In [40]:
old_platform = pd.read_csv('candSID_PanAfID_translations_old_platform_2021_11_27.txt', delimiter='\t')
old_platform['subdir'] = old_platform['new.file.name'].str.split('/').str[-2].str.lower().str.rstrip('+')
old_platform['video'] = old_platform['new.file.name'].str.split('/').str[-1].str.split('.').str[0].str.lower()
old_platform['subdir_video'] = old_platform['subdir'] + '/' + old_platform['video']

In [42]:
old_platform

,clip.id,site,video.id,new.file.name,subdir,video,subdir_video
0,ACP000e0ia,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_64_0690657_0641826_20150213,ek000014,taieast_64_0690657_0641826_20150213/ek000014
1,ACP000e0i4,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_64_0690657_0641826_20150213,ek000003,taieast_64_0690657_0641826_20150213/ek000003
2,ACP000e0hk,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_64_0690657_0641826_20150213,ek000027,taieast_64_0690657_0641826_20150213/ek000027
3,ACP000e0gq,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_64_0690657_0641826_20150213,ek000019,taieast_64_0690657_0641826_20150213/ek000019
4,ACP000e0h5,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_64_0690657_0641826_20150213,ek000033,taieast_64_0690657_0641826_20150213/ek000033
...,...,...,...,...,...,...,...
562800,ACP000dz1a,ngogo,Uganda_Ngogo/Ngo_E3/Ngo_vid14_0216721_0052051_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid14_0216721_0052051_20121204,pict0031,ngo_vid14_0216721_0052051_20121204/pict0031
562801,ACP000dzi5,ngogo,Uganda_Ngogo/Ngo_E3/Ngo_vid24_0216298_0052061_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid24_0216298_0052061_20130415,pict0154,ngo_vid24_0216298_0052061_20130415/pict0154
562802,ACP000ddkx,ngogo,Uganda_Ngogo/Ngo_B4/Ngo_vid17_0217712_0055433_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid17_0217712_0055433_20130416,pict0040,ngo_vid17_0217712_0055433_20130416/pict0040
562803,ACP000dmnz,ngogo,Uganda_Ngogo/Ngo_A3/Ngo_vid22_0216572_0056318_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid22_0216572_0056318_20121218,pict0056,ngo_vid22_0216572_0056318_20121218/pict0056
562804,ACP000d46v,ngogo,Uganda_Ngogo/Ngo_D4/Ngo_vid11_0217712_0053075_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid11_0217712_0053075_20130317,pict0028,ngo_vid11_0217712_0053075_20130317/pict0028

In [43]:
len(old_platform.subdir_video.unique()), len(old_platform['clip.id'].unique())

(146591, 562805)

In [44]:
annotation_df[annotation_df.max_number_chimps_per_video==1]['behavioral_context'].value_counts()

travel                     3031
tool use termites          1848
feeding                     939
resting                     551
tool use                    546
unclear                     458
tool use unknown            371
climbing                    337
camera reaction             258
displaying                  103
tool use ants                86
tool use nuts                77
tool use stone throwing      62
tool use algae               56
playing                       4
aggression                    4
grooming                      2
greeting                      1
displaying                    1
no                            1
Name: behavioral_context, dtype: int64

**Video processing: filter main annotations by files held locally**

In [45]:
all_videos = pd.DataFrame([x.split('/')[-1].split('.')[0] for x in glob('/home/dl18206/Desktop/phd/data/panaf/acp/videos/**/*.mp4', recursive=True)])
all_videos.rename({0:'ids'}, axis=1, inplace=True)

In [47]:
core_videos = pd.DataFrame([x.split('/')[-1].split('.')[0] for x in glob('/home/dl18206/Desktop/phd/data/panaf/acp/videos/core/**/*.mp4', recursive=True)])
core_videos.rename({0:'ids'}, axis=1, inplace=True)

In [48]:
other_videos = pd.DataFrame([x.split('/')[-1].split('.')[0] for x in glob('/home/dl18206/Desktop/phd/data/panaf/machine_annotations/core/raw_detections/other_detections/**/*.pkl', recursive=True)])
other_videos.rename({0:'ids'}, axis=1, inplace=True)
local_videos = pd.concat([core_videos, other_videos])

In [49]:
single_ape_videos = pd.DataFrame([x.split('/')[-1].split('.')[0] for x in glob('/home/dl18206/Desktop/phd/data/panaf/machine_annotations/core/tracked_detections/vfnet_annotations/vfnet_single/scaled/**/*.json', recursive=True)])
single_ape_videos.rename({0:'ids'}, axis=1, inplace=True)

In [ ]:
joined_df = all_videos.join(old_platform.set_index('clip.id'), on='ids', how='inner')
joined_df = joined_df.join(annotation_df.set_index('subdir_video'), on='subdir_video')

In [35]:
joined_df.ids.unique().__len__(), joined_df.subdir_video.unique().__len__()

NameError: name 'joined_df' is not defined

In [10]:
joined_df

,ids,site,video.id,new.file.name,subdir,video,subdir_video,new_row_id,country,research_site,...,tool_use,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,Unnamed: 36,Unnamed: 37
0,ACP000fw73,taieast,TaiEast_MarieLyne/TaiEast_MarieLyne_CAMERA TRA...,Y:/primpanaf/22_Publications/03_MarieLyne Desp...,taieast_43_0690693_0644772_20141217,ek000004,taieast_43_0690693_0644772_20141217/ek000004,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACP000axnf,budongo,Uganda_Budongo/Bud_C2/Bud_cam9_336740_190667_2...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam9_336740_190667_20120731,pict0107,bud_cam9_336740_190667_20120731/pict0107,874,uganda,budongo,...,NaN,NaN,NaN,NaN,resting,NaN,NaN,60s_video,NaN,NaN
2,ACP000b680,budongo,Uganda_Budongo/Bud_B2/Bud_cam10_336884_191472_...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam10_336884_191472_20120803,pict0059,bud_cam10_336884_191472_20120803/pict0059,48,uganda,budongo,...,NaN,NaN,NaN,NaN,feeding,NaN,feeding on figs,60s_video,NaN,NaN
3,ACP0006bzj,kayan,Senegal_Kayan/Kay_E6/Kay_vid21_0797703_1462464...,Y:/primpanaf/07_DATA/13_Senegal/Kayan/Kayan_FI...,kay_vid21_0797703_1462464_20120821,pict0019,kay_vid21_0797703_1462464_20120821/pict0019,118,senegal,kayan,...,NaN,NaN,NaN,NaN,unclear,NaN,NaN,60s_video,NaN,NaN
3,ACP0006bzj,kayan,Senegal_Kayan/Kay_E6/Kay_vid21_0797703_1462464...,Y:/primpanaf/07_DATA/13_Senegal/Kayan/Kayan_FI...,kay_vid21_0797703_1462464_20120821,pict0019,kay_vid21_0797703_1462464_20120821/pict0019,119,senegal,kayan,...,NaN,NaN,NaN,NaN,unclear,NaN,ventral infant,60s_video,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,ACP0005ugj,grebo_sala,Liberia_Grebo_Part1/Gbo_5D/Gbo_Vid17_661126_60...,Y:/primpanaf/07_DATA/10_Liberia/TRS/Grebo/GREB...,gbo_vid17_661126_606589_20131002,pict0014,gbo_vid17_661126_606589_20131002/pict0014,40,liberia,grebo_sala,...,NaN,NaN,NaN,NaN,travel,NaN,runs past quickly in background,60s_video,NaN,NaN
19974,ACP0005ugj,grebo_sala,Liberia_Grebo_Part1/Gbo_5D/Gbo_Vid17_661126_60...,Y:/primpanaf/07_DATA/10_Liberia/TRS/Grebo/GREB...,gbo_vid17_661126_606589_20131002,pict0014,gbo_vid17_661126_606589_20131002/pict0014,41,liberia,grebo_sala,...,NaN,NaN,NaN,NaN,travel,NaN,runs past quickly in background,60s_video,NaN,NaN
19975,ACP000bbtu,budongo,Uganda_Budongo/Bud_B2/Bud_cam6_336740_191880_2...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam6_336740_191880_20121127,pict0050,bud_cam6_336740_191880_20121127/pict0050,791,uganda,budongo,...,NaN,NaN,NaN,NaN,climbing,NaN,NaN,60s_video,NaN,NaN
19975,ACP000bbtu,budongo,Uganda_Budongo/Bud_B2/Bud_cam6_336740_191880_2...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam6_336740_191880_20121127,pict0050,bud_cam6_336740_191880_20121127/pict0050,792,uganda,budongo,...,NaN,NaN,NaN,NaN,climbing,NaN,NaN,60s_video,NaN,NaN
19976,ACP000b91o,budongo,Uganda_Budongo/Bud_B2/Bud_cam3_336752_191864_2...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam3_336752_191864_20121127,pict0094,bud_cam3_336752_191864_20121127/pict0094,747,uganda,budongo,...,NaN,NaN,NaN,NaN,climbing,NaN,NaN,60s_video,NaN,NaN

In [11]:
single_ape_annotations = joined_df[joined_df.max_number_chimps_per_video==1]
single_ape_annotations.ids.unique().__len__(), single_ape_annotations.subdir_video.unique().__len__()

(6747, 1767)

In [12]:
single_ape_core_annotations = single_ape_annotations[single_ape_annotations.ids.isin(single_ape_videos.ids)]
single_ape_core_annotations.ids.unique().__len__()

2634

**Convert data into usable labels**

In [13]:
single_ape_core_annotations.columns

Index(['ids', 'site', 'video.id', 'new.file.name', 'subdir', 'video',
       'subdir_video', 'new_row_id', 'country', 'research_site', 'genus',
       'species', 'cam_coverage_area', 'location_metadata', 'habitat',
       'utm_zone', 'utm_long', 'utm_lat', 'cam_id', 'vid_res', 'vid_duration',
       'panaf_datasheet_comments', 'year', 'month', 'day', 'time_hr',
       'time_min', 'cell_id', 'subfolder', 'video_file_name', 'event_id',
       'min_number_chimps_per_video', 'max_number_chimps_per_video',
       'age_class', 'sex', 'tool_use', 'vocalization', 'bipedal',
       'camera_reaction', 'behavioral_context', 'other_species',
       'additional_comments', 'record_type', 'Unnamed: 36', 'Unnamed: 37'],
      dtype='object')

In [ ]:
d = {'yes': True, 'no': False}
single_ape_core_annotations.tool_use = single_ape_core_annotations.tool_use.map(d)
single_ape_core_annotations.vocalization = single_ape_core_annotations.vocalization.map(d)
single_ape_core_annotations.bipedal = single_ape_core_annotations.bipedal.map(d)
single_ape_core_annotations.camera_reaction = single_ape_core_annotations.camera_reaction.map(d)
single_ape_core_annotations.fillna(False, inplace=True)

In [18]:
context_df = single_ape_core_annotations.behavioral_context.str.get_dummies('|').replace({
   0: False,
   1: True
})

In [19]:
context_df.head()

,camera reaction,climbing,displaying,feeding,no,resting,tool use,tool use nuts,tool use stone throwing,tool use termites,travel,unclear
6,False,False,False,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,True,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,True
19,False,False,False,True,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,True,False

In [20]:
final_df = pd.concat([single_ape_core_annotations, context_df], axis=1)
final_df.rename(
    {
    'tool_use': 'column_tool_use', 
    'vocalization': 'column_vocalization',
    'bipedal': 'column_bipedal',
    'camera_reaction': 'column_camera_reaction', 
    }, axis=1, inplace=True
)

In [21]:
final_df.columns

Index(['ids', 'site', 'video.id', 'new.file.name', 'subdir', 'video',
       'subdir_video', 'new_row_id', 'country', 'research_site', 'genus',
       'species', 'cam_coverage_area', 'location_metadata', 'habitat',
       'utm_zone', 'utm_long', 'utm_lat', 'cam_id', 'vid_res', 'vid_duration',
       'panaf_datasheet_comments', 'year', 'month', 'day', 'time_hr',
       'time_min', 'cell_id', 'subfolder', 'video_file_name', 'event_id',
       'min_number_chimps_per_video', 'max_number_chimps_per_video',
       'age_class', 'sex', 'column_tool_use', 'column_vocalization',
       'column_bipedal', 'column_camera_reaction', 'behavioral_context',
       'other_species', 'additional_comments', 'record_type', 'Unnamed: 36',
       'Unnamed: 37', 'camera reaction', 'climbing', 'displaying', 'feeding',
       'no', 'resting', 'tool use', 'tool use nuts', 'tool use stone throwing',
       'tool use termites', 'travel', 'unclear'],
      dtype='object')

In [22]:
filtered_final = final_df[(final_df.behavioral_context != 'no') & (final_df.behavioral_context != 'unclear')]
filtered_final['multiclass_labels'] = filtered_final.behavioral_context.astype('category').cat.codes

<ipython-input-22-f27cbc826e99>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final['multiclass_labels'] = filtered_final.behavioral_context.astype('category').cat.codes

In [30]:
filtered_final.behavioral_context.value_counts()

feeding                    1479
travel                      369
tool use nuts               225
resting                     201
tool use                    167
climbing                     69
camera reaction              68
displaying                    7
tool use stone throwing       6
tool use termites             2
Name: behavioral_context, dtype: int64

In [24]:
final_df.behavioral_context.unique()

array(['feeding', 'resting', 'unclear', 'travel', 'camera reaction',
       'tool use nuts', 'tool use', 'climbing', 'tool use stone throwing',
       'displaying', 'tool use termites', 'no'], dtype=object)

In [77]:
# Train test splits + labels
from sklearn.model_selection import train_test_split
X = filtered_final.ids.values
y = filtered_final.multiclass_labels.values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [78]:
filtered_final['split'] = filtered_final.ids.apply(lambda x: 'train' if x in X_train else 'test')

<ipython-input-78-2798e97c6414>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final['split'] = filtered_final.ids.apply(lambda x: 'train' if x in X_train else 'test')

In [81]:
filtered_final.to_csv('single_ape_subset_labels.csv')

In [85]:
filtered_final[filtered_final.split=='test']

,ids,site,video.id,new.file.name,subdir,video,subdir_video,new_row_id,country,research_site,...,no,resting,tool use,tool use nuts,tool use stone throwing,tool use termites,travel,unclear,multiclass_labels,split
31,ACP0006v6o,kayan,Senegal_Kayan/Kay_I10/Kay_vid33_0801167_145919...,Y:/primpanaf/07_DATA/13_Senegal/Kayan/Kayan_FI...,kay_vid33_0801167_1459199_20130323,pict0053,kay_vid33_0801167_1459199_20130323/pict0053,265,senegal,kayan,...,False,False,True,False,False,False,False,False,5,test
54,ACP000b6jz,budongo,Uganda_Budongo/Bud_B2/Bud_cam10_336884_191472_...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam10_336884_191472_20120803,pict0109,bud_cam10_336884_191472_20120803/pict0109,72,uganda,budongo,...,False,False,False,False,False,False,False,False,3,test
61,ACP000b6nf,budongo,Uganda_Budongo/Bud_B2/Bud_cam28_336939_191998_...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam28_336939_191998_20120913,pict0196,bud_cam28_336939_191998_20120913/pict0196,689,uganda,budongo,...,False,False,False,False,False,False,False,False,3,test
80,ACP000b787,budongo,Uganda_Budongo/Bud_B2/Bud_cam28_336939_191998_...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam28_336939_191998_20120913,pict0122,bud_cam28_336939_191998_20120913/pict0122,652,uganda,budongo,...,False,False,False,False,False,False,False,False,3,test
83,ACP000b3kb,budongo,Uganda_Budongo/Bud_B2/Bud_cam10_336884_191472_...,Y:/primpanaf/07_DATA/16_Uganda/Budongo/Budongo...,bud_cam10_336884_191472_20120821,pict0022,bud_cam10_336884_191472_20120821/pict0022,104,uganda,budongo,...,False,False,False,False,False,False,False,False,3,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19809,ACP000dknz,ngogo,Uganda_Ngogo/Ngo_A3/Ngo_vid03_0216558_0056315_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid03_0216558_0056315_20130211,pict0012,ngo_vid03_0216558_0056315_20130211/pict0012,1777,uganda,ngogo,...,False,False,False,False,False,False,False,False,3,test
19862,ACP000d6ld,ngogo,Uganda_Ngogo/Ngo_F2/Ngo_vid23_0215958_0050905_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid23_0215958_0050905_20130113,pict0060,ngo_vid23_0215958_0050905_20130113/pict0060,1261,uganda,ngogo,...,False,False,False,False,False,False,False,False,3,test
19919,ACP00038mx,taie,IvoryCoast_TaiE/B3/TAI-E_CAM_15_0681257_065409...,Y:/primpanaf/07_DATA/9_Ivory Coast/Tai/TaiE_FI...,taie_cam15_0681168_0653714_20130908,ek000145,taie_cam15_0681168_0653714_20130908/ek000145,274,cotedivoire,taie,...,False,False,False,False,False,False,False,False,3,test
19937,ACP000dkqw,ngogo,Uganda_Ngogo/Ngo_A3/Ngo_vid03_0216558_0056315_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid03_0216558_0056315_20130211,pict0004,ngo_vid03_0216558_0056315_20130211/pict0004,1769,uganda,ngogo,...,False,False,False,False,False,False,False,False,3,test
19961,ACP000drc4,ngogo,Uganda_Ngogo/Ngo_A3/Ngo_vid03_0216558_0056315_...,Y:/primpanaf/07_DATA/16_Uganda/Ngogo/NGOGO_fin...,ngo_vid03_0216558_0056315_20121201,pict0208,ngo_vid03_0216558_0056315_20121201/pict0208,814,uganda,ngogo,...,False,False,False,False,False,False,False,False,3,test

In [88]:
filtered_final.multiclass_labels.unique().__len__()

10

**Merge with chimp&see annotations**

In [ ]:
df = pd.read_excel(open('/home/dl18206/Downloads/Chimp & See master chimpanzee video list 2015-2018_OB_analysis.xlsx', 'rb'),
              sheet_name="Otto's Analysis (Plain Text)")

In [ ]:
tool_use_mask = df.Tags.apply(lambda x: 
                 ('carrying_tool' in x) or 
                 ('using_tool' in x) or 
                 ('rock_tool_use' in x) or 
                 ('holding_tool' in x) or
                 ('tool_usage' in x) or 
                 ('tool_modification' in x) or
                 ('tool_user' in x) or 
                 ('tool_use_learning' in x) or
                 ('tree_limb_tool' in x) or 
                 ('tool-usage' in x) or
                 ('chimps_using_tool' in x) or
                 ('tool_useage' in x) or 
                 ('chimp_with_tool' in x) or 
                 ('tool-using' in x) or
                 ('toolusage' in x) or 
                 ('tool_working' in x) or
                 ('log_tool' in x) or 
                 ('tree_limb_tool_use' in x) or
                 ('tools_use' in x) or
                 ('chimp_tool_use' in x) or 
                 ('tool_work' in x) or 
                 ('tool_use' in x) or
                 ('nicetooluse' in x) or 
                 ('tool_using' in x) or
                 ('tools' in x) or 
                 ('tool-use' in x) or
                 ('termite-tool' in x) or                              
                 ('tool' in x) or 
                 ('tooluse' in x) or 
                 ('chimptoolusage' in x) or
                 ('usingtool' in x) or 
                 ('chimptooluse' in x) or
                 ('ool_use' in x) or 
                 ('toool_usage' in x) or
                 ('carrying_objects' in x) or
                 ('rocksmash' in x) or
                 ('cracking' in x) or
                 ('stone_tool_use' in x) or
                 ('hammerstone' in x) or
                 ('stone' in x) or
                 ('rock' in x) or
                 ('hammer' in x) or
                 ('cracking_nuts' in x) or
                 ('breakingnut' in x) or
                 ('nut_cracking' in x) or
                 ('nutcracking' in x) or
                 ('crackingnuts' in x) or
                 ('woodhammer' in x))

feeding_mask = df.Tags.apply(lambda x: 
                 ('eatingintree' in x) or 
                 ('eating' in x) or
                 ('clay_eating' in x) or
                 ('chimp_with_young_feeding_on_ground' in x) or
                 ('feeding' in x) or 
                 ('insects' in x) or
                 ('chimpcollectingfood' in x) or
                 ('fruit' in x) or 
                 ('applejack' in x) or
                 ('wood_' in x) or 
                 ('wood_eating' in x) or 
                 ('eating_wood' in x) or 
                 ('wood_chewing' in x) or
                 ('wood_feeding' in x) or 
                 ('wood-eating' in x) or
                 ('woodeating' in x) or 
                 ('woord_eating' in x) or
                 ('wwod-eating' in x) or 
                 ('eatingbark' in x) or
                 ('barking' in x) or 
                 ('bark-eating' in x) or
                 ('bark_eating' in x) or 
                 ('tree_gnawing' in x) or                              
                 ('stripping_bark' in x) or
                 ('nut_pick' in x) or 
                 ('nutpick' in x) or
                 ('nut' in x) or 
                 ('nuts' in x) or
                 ('termites' in x) or 
                 ('termite_mound' in x) or 
                 ('termitefishing' in x) or 
                 ('female_on_termite_mound' in x))
                             
swelling_mask = df.Tags.apply(lambda x: 
                           ('femaleswelling' in x) or 
                           ('max_swelling' in x) or 
                           ('sexual_swelling' in x) or 
                           ('max-swelling' in x) or 
                           ('big_swelling' in x) or 
                           ('swelling' in x) or 
                           ('extreme_swelling' in x) or                          
                           ('same_swelling' in x))

camera_mask = df.Tags.apply(lambda x: 
                 ('camera_interaction' in x) or 
                 ('camera_' in x) or 
                 ('camera_aware' in x) or 
                 ('camera_touch' in x) or
                 ('camera-reaction' in x) or 
                 ('camerainteraction' in x) or
                 ('camera_reactrion' in x) or 
                 ('camera_stare' in x) or
                 ('camera_reaction' in x) or 
                 ('camerareaction' in x) or
                 ('cam_reaction' in x) or 
                 ('camera_reaction_infants' in x) or
                 ('camera-aware' in x) or 
                 ('touchcam' in x) or   
                 ('camea_reaction' in x) or    
                 ('camara_reaction' in x) or    
                 ('cam_touch' in x) or                                
                 ('caerma_reaction' in x) or
                 ('selfie' in x) or                                
                 ('chimp_selfie' in x))

climbing_mask = df.Tags.apply(lambda x: 
                           ('climbing_in_tree' in x) or 
                           ('treeclimbing' in x) or 
                           ('climbing' in x) or 
                           ('climbing_tree' in x) or 
                           ('tree' in x) or
                           ('climping' in x) or
                           ('inatree' in x))


bipedal_mask = df.Tags.apply(lambda x: 
                           ('pibedal' in x) or 
                           ('upright_walking' in x) or 
                           ('chimp_just_standing' in x) or 
                           ('chimp_standing' in x) or 
                           ('standing' in x) or 
                           ('bipedal' in x))

night_mask = df.Tags.apply(lambda x: 
                           ('chimatnight' in x) or 
                           ('nightchimps' in x) or 
                           ('nightmeal' in x) or 
                           ('nightfeeding' in x) or 
                           ('nightchimp' in x) or 
                           ('nightfeeding' in x) or 
                           ('night_chimp' in x))

In [ ]:
df['tool_use'] = tool_use_mask
df['feeding'] = feeding_mask
df['climbing'] = climbing_mask
df['swelling'] = swelling_mask
df['bipedal'] = bipedal_mask
df['camera'] = camera_mask
df['night'] = night_mask

In [ ]:
df.ID.unique().__len__()

In [ ]:
df.head()

In [ ]:
tmp.drop(
    columns=['video.id', 'new.file.name', 'subdir', 'video',
             'subdir_video', 'new_row_id', 'utm_zone', 'utm_long',
             'utm_lat', 'cam_id', 'vid_res', 'vid_duration',
             'panaf_datasheet_comments', 'year', 'month', 'day', 'time_hr',
             'time_min', 'cell_id', 'subfolder', 'video_file_name', 'event_id',
             'min_number_chimps_per_video', 'record_type', 'Unnamed: 36',
             'Unnamed: 37'], inplace=True)

**Annotation processing and tracklet counting**

In [ ]:
single_ape_core_annotations

In [ ]:
def get_tracklet_df(annotation_path):
    # Generated by single_ape_subset dirs
    annotations = glob(f'{annotation_path}/**/*.json', recursive=True)
    
    ids, tracklet_num, idxs_st = [], [], []

    for a in annotations:
        with open(a, 'rb') as handle:
            data = json.load(handle)
            
        name = data['video']
        
        if not data['annotations']:
            ids.append(name)
            tracklet_num.append(0)
            idxs_st.append([])
            continue
        
        idxs = []

        for frame in data['annotations']:
            if(frame['detections'][0]['ape_id'] == 0):
                idxs.append(frame['frame_id'])                
                
        tracklets = 1
        start_idxs = [idxs[0]]

        for i in range(len(idxs)-1):
            if(idxs[i+1] - idxs[i] == 1):
                continue
            else:
                tracklets+=1
                start_idxs.append(idxs[i])
                start_idxs.append(idxs[i+1])
        start_idxs.append(idxs[-1])

        ids.append(name)
        tracklet_num.append(tracklets)
        idxs_st.extend([start_idxs])
    
    df = pd.DataFrame([ids, tracklet_num, idxs_st]).transpose()
    df.columns = ['id', 'tracklet_num', 'indexes']
    return df

In [ ]:
tdf = get_tracklet_df('/home/dl18206/Desktop/phd/data/panaf/single_ape_subset/annotations/')
tdf = tdf[tdf.tracklet_num>0]

In [ ]:
single_ape_core_annotations = single_ape_core_annotations[single_ape_core_annotations.ids.isin(tdf.id)]

In [ ]:
single_ape_core_annotations.drop(
    columns=['video.id', 'new.file.name', 'subdir', 'video',
             'subdir_video', 'new_row_id', 'utm_zone', 'utm_long',
             'utm_lat', 'cam_id', 'vid_res', 'vid_duration',
             'panaf_datasheet_comments', 'year', 'month', 'day', 'time_hr',
             'time_min', 'cell_id', 'subfolder', 'video_file_name', 'event_id',
             'min_number_chimps_per_video', 'record_type', 'Unnamed: 36',
             'Unnamed: 37'], inplace=True)

In [ ]:
single_ape_core_annotations.columns

In [ ]:
single_ape_core_annotations.behavioral_context.value_counts()

In [ ]:
single_ape_core_annotations.bipedal.value_counts()

In [ ]:
single_ape_core_annotations

****Address later****

In [ ]:
# Finding videos we dont have
from tqdm import tqdm

acp_old_platform = old_platform[old_platform['clip.id'].isin(core_videos.ids.values)]

def get_subdir_video(acp_old_platform, acp_code):
    subdir_video = acp_old_platform[acp_old_platform['clip.id']==acp_code]['subdir_video'].iloc[0]
    return annotation_df[annotation_df.subdir_video==subdir_video]

def func(acp_old_platform, core_videos):
    cnt = 0
    not_got = []
    for i in tqdm(core_videos.ids.values):
        try:
            get_subdir_video(acp_code=i).iloc[0]
        except:
            not_got.append(i)
    dont_have_df = acp_old_platform[acp_old_platform['clip.id'].isin(not_got)]
    return cnt, not_got

In [ ]:
dont_have_df.site.value_counts()

In [ ]:
dont_have_df[dont_have_df['site']=='bwindi']['video.id'].iloc[0]

In [ ]:
acp_old_platform[acp_old_platform['clip.id']=='ACP000fwa2']['new.file.name'].iloc[0]

In [ ]:
df = pd.read_csv('candSID_PanAfID_translations_old_platform_2020_12_18.csv')
df.head()

In [ ]:
df[df['clip.id']=='ACP000fwa2']['video.id'].iloc[0], df[df['clip.id']=='ACP000fwa2']['new.video.id'].iloc[0]