In [64]:
import pandas as pd
from glob import glob

In [65]:
# Translation table
translation_df = pd.read_csv('/home/dl18206/Desktop/phd/data/panaf/chimp_and_see/data/external/candSID_PanAfID_translations_old_platform_2021_11_27.csv')
translation_df['video'] = translation_df['clip.id'].str.lower()
translation_df['video_id'] = translation_df['video.id'].str.lower()
translation_df['new_file_name'] = translation_df['new.file.name'].str.lower()
translation_df.drop(columns=['Unnamed: 0', 'clip.id', 'video.id', 'new.file.name'], inplace=True)
translation_df.head(1)

,site,video,video_id,new_file_name
0,taieast,acp000e0ia,taieast_marielyne/taieast_marielyne_camera tra...,y:/primpanaf/22_publications/03_marielyne desp...

In [66]:
# Maureens annotations
csv_files = glob('/home/dl18206/Desktop/phd/data/panaf/maureen_annotations/data/sites/csv/**/*.csv', recursive=True)
sorted_csv_files = sorted(csv_files, key=lambda x: x.split('/')[-1])
initialiser, remainder = sorted_csv_files[0], sorted_csv_files[1:]
df = pd.read_csv(initialiser, encoding="ISO-8859-1")
for file in remainder:
    site = pd.read_csv(file, encoding="ISO-8859-1")
    df = pd.concat([df, site])
df['subdir_video'] = df.subfolder.astype(str) + '_' + df.video_file_name.astype(str)
df['subdir_video'] = df.subdir_video.str.lower()
df['subdir_video'] = df.subdir_video.str.split('.').str[0]
df.head(1)

,new_row_id,country,research_site,genus,species,cam_coverage_area,location_metadata,habitat,utm_zone,utm_long,...,sex,tool_use,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,subdir_video
0,1,mali,bafing,Pan,troglodytes verus,9.87,trail,forest on rock,29n,342661.0,...,male,no,no,no,no,travel,NaN,Not very clear screen,60s_video,baf_vid1_0342661_1432807_20141103_11160014

In [67]:
p500_df = pd.read_csv('p500_video_translation.csv')
p500_df.rename(columns={'zooniverse_id':'video'}, inplace=True)
p500_df.video = p500_df.video.str.lower()
p500_df.head(1)

,obfu_id,video,filename,species,group__name,group_num,metadata__duration,metadata__start_time
0,aajn6zzbph,acp000b3dy,ACP000b3dy.mp4,chimpanzee,cold-fire,1,15.0,0.0

In [68]:
acp_trans_df = p500_df.merge(translation_df, on='video')
# Create subdir_video column to allow downstream merging with 
acp_trans_df['subdir_video'] = acp_trans_df.new_file_name.apply(lambda x: '_'.join(x.split('/')[-2:]))
acp_trans_df['subdir_video'] = acp_trans_df.subdir_video.apply(lambda x: x.split('.')[0])
acp_trans_df.drop(columns=['video_id', 'new_file_name'], inplace=True)

In [63]:
acp_trans_df

,obfu_id,video,filename,species,group__name,group_num,metadata__duration,metadata__start_time,site,subdir_video
0,aajn6zzbph,acp000b3dy,ACP000b3dy.mp4,chimpanzee,cold-fire,1,15.0,0.0,budongo,bud_cam10_336884_191472_20120821_pict0011
1,dpw52gwsl1,acp0005uy3,ACP0005uy3.mp4,chimpanzee,lingering-shape-9,8,15.0,30.0,grebo_sala,gbo_vid4_660653_606290_20130928_pict0017
2,jkf4v2wlfx,acp000086p,ACP000086p.mp4,chimpanzee,quiet-wood-1,10,60.0,15.0,bili,bili_vid03_241949_479203_20120929_pict0032
3,tsfcsskzig,acp0003r9t,ACP0003r9t.mp4,chimpanzee,muddy-frost-7,9,15.0,30.0,tair,tair_cam29_685375_649767_20130903_ek000237
4,d5d1ioy7ja,acp00050c2,ACP00050c2.mp4,chimpanzee,crimson-dew-8,3,15.0,15.0,east_nimba,nim_vid23_0548309_0822019_20131120_ek000072
...,...,...,...,...,...,...,...,...,...,...
495,dvk4t8zjir,acp0002ube,ACP0002ube.mp4,chimpanzee,red-water-6,11,15.0,0.0,taie,taie_cam05_0679610_0655760_20130531_ek000411
496,ftshmgbzk4,acp000bj97,ACP000bj97.mp4,chimpanzee,restless-star,12,15.0,0.0,bwindi,bwi_vid7_806110_9885227_20120911_pict0162
497,0hu96jv2as,acp000exsz,ACP000exsz.mp4,chimpanzee,aged-violet,0,15.0,30.0,taieast,taieast_41_0692888_0643632_20140811+_pict0070
498,hdj8vi3tjm,acp00050aa,ACP00050aa.mp4,chimpanzee,crimson-dew-8,3,15.0,0.0,east_nimba,nim_vid23_0548309_0822019_20131120_ek000054
499,aapaeob349,acp000cckm,ACP000cckm.mp4,chimpanzee,restless-star,12,15.0,15.0,bwindi,bwi_vid27_809842_9882780_20130308_pict0320

In [74]:
acp_trans_df[acp_trans_df.species=='chimpanzee']

,obfu_id,video,filename,species,group__name,group_num,metadata__duration,metadata__start_time,site,subdir_video
0,aajn6zzbph,acp000b3dy,ACP000b3dy.mp4,chimpanzee,cold-fire,1,15.0,0.0,budongo,bud_cam10_336884_191472_20120821_pict0011
1,dpw52gwsl1,acp0005uy3,ACP0005uy3.mp4,chimpanzee,lingering-shape-9,8,15.0,30.0,grebo_sala,gbo_vid4_660653_606290_20130928_pict0017
2,jkf4v2wlfx,acp000086p,ACP000086p.mp4,chimpanzee,quiet-wood-1,10,60.0,15.0,bili,bili_vid03_241949_479203_20120929_pict0032
3,tsfcsskzig,acp0003r9t,ACP0003r9t.mp4,chimpanzee,muddy-frost-7,9,15.0,30.0,tair,tair_cam29_685375_649767_20130903_ek000237
4,d5d1ioy7ja,acp00050c2,ACP00050c2.mp4,chimpanzee,crimson-dew-8,3,15.0,15.0,east_nimba,nim_vid23_0548309_0822019_20131120_ek000072
...,...,...,...,...,...,...,...,...,...,...
495,dvk4t8zjir,acp0002ube,ACP0002ube.mp4,chimpanzee,red-water-6,11,15.0,0.0,taie,taie_cam05_0679610_0655760_20130531_ek000411
496,ftshmgbzk4,acp000bj97,ACP000bj97.mp4,chimpanzee,restless-star,12,15.0,0.0,bwindi,bwi_vid7_806110_9885227_20120911_pict0162
497,0hu96jv2as,acp000exsz,ACP000exsz.mp4,chimpanzee,aged-violet,0,15.0,30.0,taieast,taieast_41_0692888_0643632_20140811+_pict0070
498,hdj8vi3tjm,acp00050aa,ACP00050aa.mp4,chimpanzee,crimson-dew-8,3,15.0,0.0,east_nimba,nim_vid23_0548309_0822019_20131120_ek000054
499,aapaeob349,acp000cckm,ACP000cckm.mp4,chimpanzee,restless-star,12,15.0,15.0,bwindi,bwi_vid27_809842_9882780_20130308_pict0320

In [73]:
acp_trans_df[acp_trans_df.species=='chimpanzee'].merge(df, on='subdir_video').video.unique().__len__()

304

In [75]:
df[]

,new_row_id,country,research_site,genus,species,cam_coverage_area,location_metadata,habitat,utm_zone,utm_long,...,sex,tool_use,vocalization,bipedal,camera_reaction,behavioral_context,other_species,additional_comments,record_type,subdir_video
0,1,mali,bafing,Pan,troglodytes verus,9.87,trail,forest on rock,29n,342661.0,...,male,no,no,no,no,travel,NaN,Not very clear screen,60s_video,baf_vid1_0342661_1432807_20141103_11160014
1,2,mali,bafing,Pan,troglodytes verus,14.00,nesting site,savannah - wooded,29n,344126.0,...,female,no,no,no,no,feeding,NaN,"Gray back, disappears at the left side",60s_video,baf_vid1_0344126_1437042_20151226_1020010
2,3,mali,bafing,Pan,troglodytes verus,14.00,nesting site,savannah - wooded,29n,344126.0,...,unclear,no,no,no,no,feeding,NaN,"Follows the above chimp, probably child of her",60s_video,baf_vid1_0344126_1437042_20151226_1020010
3,4,mali,bafing,Pan,troglodytes verus,14.00,nesting site,savannah - wooded,29n,344126.0,...,unclear,no,no,no,no,feeding,NaN,"On the ground, stands near next chimp, and the...",60s_video,baf_vid1_0344126_1437042_20151226_1020010
4,5,mali,bafing,Pan,troglodytes verus,14.00,nesting site,savannah - wooded,29n,344126.0,...,female,no,no,no,no,feeding,NaN,"Behind the tree, picks a baobabÂ´s fruit and th...",60s_video,baf_vid1_0344126_1437042_20151226_1020010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1336,1337,tanzania,ugalla_issa,Pan,troglodytes schweinfurthii,NaN,trail,forest - colonising,36s,230040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photo,uga_vid32_230040_9391979_20140823_pict0359
1337,1338,tanzania,ugalla_issa,Pan,troglodytes schweinfurthii,NaN,trail,forest - colonising,36s,230040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photo,uga_vid32_230040_9391979_20140823_pict0360
1338,1339,tanzania,ugalla_issa,Pan,troglodytes schweinfurthii,NaN,trail,forest - colonising,36s,230040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photo,uga_vid32_230040_9391979_20140823_pict0361
1339,1340,tanzania,ugalla_issa,Pan,troglodytes schweinfurthii,NaN,trail,forest - colonising,36s,230040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photo,uga_vid32_230040_9391979_20140823_pict0362
1340,1341,tanzania,ugalla_issa,Pan,troglodytes schweinfurthii,NaN,trail,forest - colonising,36s,230040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,photo,uga_vid32_230040_9391979_20140823_pict0363